-- AlterTable
ALTER TABLE "Course" ADD COLUMN     "priceBasic" INTEGER NOT NULL DEFAULT 200000,
ADD COLUMN     "priceDeluxe" INTEGER NOT NULL DEFAULT 800000,
ADD COLUMN     "pricePro" INTEGER NOT NULL DEFAULT 400000;
